# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-16 08:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default=datetime.datetime(2019, 12, 16, 8, 45, 38, 158511, tzinfo=utc), upload_to='welcome/'),
            preserve_default=False,
        ),
    ]
